import { createFileRoute } from "@tanstack/react-router";
import Blog from "@/site/pages/Blog";
import { blogPlaceholders } from "@/site/data/content";
import {
  SITE_URL,
  canonical,
  ogImage,
  breadcrumbSchema,
  faqSchema,
  type FAQItem,
} from "@/site/data/seo";

const title =
  "EMC Testing Blog | EMI/EMC Compliance Insights & Engineering Notes | CCTL";
const description =
  "Expert articles on EMI/EMC testing, compliance standards, electromagnetic compatibility tips, and emission reduction strategies from Cosmic Compliance Test Lab engineers in Coimbatore and Bangalore, India.";

const blogFaqs: FAQItem[] = [
  {
    question: "What topics does CCTL's EMC blog cover?",
    answer:
      "CCTL's blog covers practical EMC engineering topics including EMI and EMC testing fundamentals, how to prepare a product for EMC testing, emission reduction strategies, explanation of key standards such as CISPR 25 and MIL-STD-461, and guides on automotive, defence, and civilian EMC compliance.",
  },
  {
    question: "What is the difference between EMI and EMC?",
    answer:
      "EMI (Electromagnetic Interference) refers to unwanted electromagnetic disturbances generated by or affecting a device. EMC (Electromagnetic Compatibility) is the broader discipline — it covers both emission testing (what a device radiates) and immunity testing (how well it withstands external disturbances).",
  },
  {
    question: "How do I prepare my product for EMC testing?",
    answer:
      "Key preparation steps include ensuring the product is in its production-representative configuration, providing all required cables and accessories, documenting the operating modes to be tested, and understanding the applicable EMC standard. CCTL's engineering team can help review requirements before testing begins.",
  },
  {
    question: "Why do products fail EMC testing?",
    answer:
      "Common causes include poor PCB layout, inadequate shielding and grounding, insufficient filtering on power and signal lines, switching noise from power supplies, and unintended radiating structures such as long cable runs or enclosure apertures.",
  },
];

const breadcrumbs = breadcrumbSchema([
  { name: "Home", path: "/" },
  { name: "Blog", path: "/blog" },
]);

const blogListSchema = {
  "@context": "https://schema.org",
  "@type": "CollectionPage",
  "@id": `${SITE_URL}/blog#webpage`,
  name: "CCTL EMC Testing Blog",
  description,
  url: canonical("/blog"),
  mainEntity: {
    "@type": "ItemList",
    numberOfItems: blogPlaceholders.length,
    itemListElement: blogPlaceholders.map((post, i) => ({
      "@type": "ListItem",
      position: i + 1,
      url: canonical(`/blog/${post.slug}`),
      name: post.title,
    })),
  },
};

export const Route = createFileRoute("/blog/")({
  head: () => ({
    meta: [
      { title },
      { name: "description", content: description },
      {
        name: "keywords",
        content:
          "EMC testing blog, EMI EMC articles, electromagnetic compatibility guide, EMC compliance tips, how to pass EMC test, EMI vs EMC, EMC testing India, EMC standards guide",
      },
      { property: "og:title", content: title },
      { property: "og:description", content: description },
      { property: "og:url", content: canonical("/blog") },
      { property: "og:image", content: ogImage() },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
      { name: "twitter:title", content: title },
      { name: "twitter:description", content: description },
      { name: "twitter:image", content: ogImage() },
      { "script:ld+json": blogListSchema },
      { "script:ld+json": faqSchema(blogFaqs) },
      { "script:ld+json": breadcrumbs },
    ],
    links: [{ rel: "canonical", href: canonical("/blog") }],
  }),
  component: Blog,
});
